services:
  db:
    image: postgres:16-alpine
    expose:
      - 5432
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    volumes:
      - db_volumen:/var/lib/postgresql/data
    networks:
      - backend
  app:
    build: 
      context: ./FOODAPP/
      dockerfile: Dockerfile
    expose:
      - 80
    ports:
      - "8888:80"

    networks:
      - frontend
  api:
    build: 
      context: ./project-FOODAPP-API/
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - "8085:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5434/proyecto
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345678
    networks:
      - backend
      - frontend

volumes:
  db_volumen:

networks:
  backend:
  frontend: